name: CustomServerPasswordWhitelist
version: '${1.0}'
main: com.eliaswagner.customserverpasswordwhitelist.CustomServerPasswordWhitelist
api-version: '1.20'
load: STARTUP
authors: [ EliasTechnik ]
website: elias-wagner.com
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: true
      join-classpath: true